development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:8ac7026a89a95294758169ae7f24fd5c@spinyfin.redistogo.com:10541/
  channel_prefix: runbuddy_production
